// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVe5_fRdL1jJZu7qF5TZdly3rvNjeqe7Y',
    appId: '1:472035819317:web:fce929c4c79bedd5e7d67c',
    messagingSenderId: '472035819317',
    projectId: 'tamdansers',
    authDomain: 'tamdansers.firebaseapp.com',
    storageBucket: 'tamdansers.firebasestorage.app',
    measurementId: 'G-VQTG1WP462',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpQrXmBezLXqcX2exedZz6kuoCmwvc2wM',
    appId: '1:472035819317:android:1536da06e95f232ee7d67c',
    messagingSenderId: '472035819317',
    projectId: 'tamdansers',
    storageBucket: 'tamdansers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJGhuYXw1wHytE5acKdLJj3yiGTwhNFCA',
    appId: '1:472035819317:ios:ee118194d930105fe7d67c',
    messagingSenderId: '472035819317',
    projectId: 'tamdansers',
    storageBucket: 'tamdansers.firebasestorage.app',
    iosBundleId: 'com.example.tamdansersLv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJGhuYXw1wHytE5acKdLJj3yiGTwhNFCA',
    appId: '1:472035819317:ios:ee118194d930105fe7d67c',
    messagingSenderId: '472035819317',
    projectId: 'tamdansers',
    storageBucket: 'tamdansers.firebasestorage.app',
    iosBundleId: 'com.example.tamdansersLv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVe5_fRdL1jJZu7qF5TZdly3rvNjeqe7Y',
    appId: '1:472035819317:web:d0a7a68b9d607e10e7d67c',
    messagingSenderId: '472035819317',
    projectId: 'tamdansers',
    authDomain: 'tamdansers.firebaseapp.com',
    storageBucket: 'tamdansers.firebasestorage.app',
    measurementId: 'G-WHS2L54CD0',
  );
}
